#!/usr/bin/env python3
"""
csa_decompile.py — ModLoader CSA -> Pseudo-C helper
Parses GTA V CSA assembly (text) and emits readable pseudo-C + call graph.

Usage:
  python3 tools/csa_decompile.py --in ModLoader.csa --out docs/ModLoader_pseudo.c --graph docs/callgraph.dot
  python3 tools/csa_decompile.py --explain Label_1835 Label_3 --in ModLoader.csa
  python3 tools/csa_decompile.py --stats --in ModLoader.csa
"""
import re, argparse, collections, os, textwrap
from pathlib import Path

OP_DESC = {
    "Push_0":"push 0", "Push_1":"push 1", "Push_2":"push 2", "Push_3":"push 3",
    "Push_4":"push 4","Push_5":"push 5","Push_6":"push 6","Push_7":"push 7","Push_-1":"push -1",
    "fPush_0.0":"push 0.0f","fPush_1.0":"push 1.0f",
    "Add":"a+b","Sub":"a-b","fAdd":"a+b (float)","fSub":"a-b (float)","fMult":"a*b (float)","fDiv":"a/b",
    "Dup":"dup","Drop":"drop","Not":"!a","Or":"a||b","And":"a&&b",
    "CmpEq":"a==b","CmpNe":"a!=b",
}

def parse(path):
    with open(path, encoding='utf-8', errors='replace') as f:
        lines = [l.rstrip('\r\n') for l in f]
    return lines

def analyze(lines):
    natives = collections.Counter()
    ops = collections.Counter()
    labels = {}
    funcs = []
    calls = collections.Counter()
    jumps = collections.Counter()
    strings = collections.Counter()
    for idx,l in enumerate(lines):
        s=l.strip()
        if not s: continue
        op = s.split()[0]
        ops[op]+=1
        if s.startswith(':'):
            labels[s[1:]]=idx
        if s.startswith('Function'):
            funcs.append((s, idx))
        m=re.search(r'CallNative\s+"([^"]+)"', s)
        if m: natives[m.group(1)]+=1
        m=re.search(r'Call\s+@(\w+)', s)
        if m: calls[m.group(1)]+=1
        m=re.search(r'Jump\w*\s+@(\w+)', s)
        if m: jumps[m.group(1)]+=1
        m=re.search(r'PushString\s+"([^"]*)"', s)
        if m: strings[m.group(1)]+=1
    return dict(natives=natives, ops=ops, labels=labels, funcs=funcs, calls=calls, jumps=jumps, strings=strings)

def pseudo_for_label(lines, label, labels, ctx=80):
    if label not in labels:
        return f"// label {label} not found"
    idx=labels[label]
    out=[]
    out.append(f"// ===== {label} @ line {idx} =====")
    # if next line is Function, show it and start after
    start=idx+1
    if start < len(lines) and lines[start].strip().startswith('Function'):
        out.append(f"// {lines[start].strip()}  // function header: params/locals")
        start+=1
    else:
        # otherwise label itself is jump target, show previous Function if any
        for j in range(idx, max(-1, idx-6), -1):
            if lines[j].strip().startswith('Function'):
                out.append(f"// {lines[j].strip()}  // function header (preceding)")
                break
    for i in range(start, min(len(lines), start+ctx+1)):
        l=lines[i]
        s=l.strip()
        if not s:
            out.append("")
            continue
        if s.startswith(':'):
            out.append(f"\n{s}  // next label")
            break
        if s.startswith('Function'):
            out.append(f"\n{s}  // next function")
            break
        comment=""
        if s.startswith('CallNative'):
            m=re.search(r'"([^"]+)"\s+(\d+)\s+(\d+)', s)
            if m:
                name, argc, retc = m.groups()
                comment = f"// native {name}({argc} args) -> {retc} ret"
        elif s.startswith('Call @'):
            comment="// call"
        elif s.startswith('Jump'):
            comment="// goto"
        elif s.startswith('PushString'):
            m=re.search(r'"([^"]*)"', s)
            if m and len(m.group(1))>60:
                comment="// (long string)"
        elif s.startswith('StaticSet'):
            comment="// static store"
        elif s.startswith('StaticGet'):
            comment="// static load -> push"
        elif 'pSet' in s:
            comment="// *addr = val (global write)"
        elif s.startswith('Switch'):
            comment="// switch"
        out.append(f"{l:<60} {comment}")
        if s.startswith('Return'):
            out.append(f"// return")
            break
    return "\n".join(out)

def emit_pseudo(lines, labels, out_path, max_funcs=300):
    with open(out_path,'w',encoding='utf-8') as out:
        out.write("// ModLoader.csa -> Pseudo-C (auto)\n")
        out.write("// Stack machine -> C-like pseudo. Stack comments show effect.\n")
        out.write("// Generated by tools/csa_decompile.py\n\n")
        out.write("// Helpers: Static1[512], Static2[512], Frame[], Stack[]\n")
        out.write("// CallNative maps to Rockstar natives, see docs/natives.txt\n\n")
        # emit each function label
        for label, idx in sorted(labels.items(), key=lambda x:x[1]):
            # only emit labels that are Function entries or heavily called
            is_func=False
            # check next line after label is Function ?
            if idx+1 < len(lines) and lines[idx+1].startswith('Function'):
                is_func=True
            # also if called >=2 times, emit brief header
            if not is_func and idx>5:
                # check if this label is target of Call (not Jump)
                pass
            if is_func:
                hdr=lines[idx+1].strip() if idx+1<len(lines) else ''
                # parse Function a b c
                parts=hdr.split()
                params = parts[2] if len(parts)>2 else "?"
                localsc = parts[3] if len(parts)>3 else "?"
                out.write(f"\n// {'='*70}\n")
                out.write(f"// FUNCTION {label}  (line {idx}) : {hdr}  // params={params} locals={localsc}\n")
                out.write(f"void {label}() {{ // {hdr}\n")
                # emit body until Return or next :Label (skip the Function header line itself)
                depth=1
                for i in range(idx+2, len(lines)):
                    s=lines[i].strip()
                    if not s:
                        out.write("\n")
                        continue
                    if s.startswith(':Label'):
                        # next function/label — close
                        out.write("}\n")
                        break
                    if s.startswith('Function'):
                        out.write("}\n")
                        break
                    if s.startswith('Return'):
                        out.write(f"  {s}; // return\n")
                        out.write("}\n")
                        break
                    # translate to pseudo with indent
                    indent="  "
                    pseudo=s
                    # add C-like hints
                    if s.startswith('CallNative'):
                        m=re.search(r'"([^"]+)"\s+(\d+)\s+(\d+)', s)
                        if m:
                            name=m.group(1)
                            pseudo=f"{name}(); // {s}"
                    elif s.startswith('Call @'):
                        mm=re.search(r'@(\w+)', s)
                        tgt=mm.group(1) if mm else "?"
                        pseudo=f"{tgt}(); // {s}"
                    elif s.startswith('Jump'):
                        mm=re.search(r'@(\w+)', s)
                        tgt=mm.group(1) if mm else "?"
                        pseudo=f"goto {tgt}; // {s}"
                    elif s.startswith('Switch'):
                        pseudo=f"switch(pop()) {s[6:]} // {s}"
                    elif s.startswith('PushString'):
                        mm=re.search(r'"([^"]*)"', s)
                        txt=mm.group(1)[:80] if mm else ""
                        pseudo=f'push("{txt}"); // {s[:80]}'
                    elif s.startswith('fPush') or s.startswith('Push'):
                        pseudo=f"push {s};"
                    elif s.startswith('StaticSet'):
                        pseudo=f"Static[{s.split()[1]}] = pop(); // {s}"
                    elif s.startswith('StaticGet'):
                        pseudo=f"push(Static[{s.split()[1]}]); // {s}"
                    elif s.startswith('getF1'):
                        pseudo=f"push(Frame[{s.split()[1]}]); // {s}"
                    elif s.startswith('setF1'):
                        pseudo=f"Frame[{s.split()[1]}] = pop(); // {s}"
                    out.write(f"{indent}{pseudo}\n")
                # safety close
                if out.tell()>0 and not pseudo.strip().endswith('}'):
                    pass
        # also emit non-function hot labels as blocks
        out.write("\n// EOF\n")

def main():
    ap=argparse.ArgumentParser()
    ap.add_argument('--in', dest='inp', default='ModLoader.csa')
    ap.add_argument('--out', dest='out', default=None)
    ap.add_argument('--graph', dest='graph', default=None)
    ap.add_argument('--explain', nargs='*', default=None, help='labels to explain')
    ap.add_argument('--stats', action='store_true')
    ap.add_argument('--pseudo-lines', type=int, default=80)
    args=ap.parse_args()

    inp = Path(args.inp)
    if not inp.exists():
        # try relative to repo root
        inp = Path('/home/user/Modding') / args.inp
    lines=parse(str(inp))
    info=analyze(lines)

    if args.stats or not args.explain and not args.out and not args.graph:
        args.stats=True
    if args.stats:
        print(f"Lines: {len(lines)}  Functions: {len(info['funcs'])}  Labels: {len(info['labels'])}")
        print("\nTop Ops:")
        for k,v in info['ops'].most_common(25):
            print(f"  {k:15} {v}")
        print("\nTop Natives (top 20):")
        for k,v in info['natives'].most_common(20):
            print(f"  {k:40} {v}")
        print("\nTop Calls:")
        for k,v in info['calls'].most_common(20):
            print(f"  {k:20} {v}")
        print("\nUnique strings:", len(info['strings']))

    if args.explain:
        for lbl in args.explain:
            lbl=lbl.lstrip('@').lstrip(':')
            print("\n"+"="*80)
            print(pseudo_for_label(lines, lbl, info['labels'], ctx=args.pseudo_lines))
    if args.out:
        outp=Path(args.out)
        outp.parent.mkdir(parents=True, exist_ok=True)
        emit_pseudo(lines, info['labels'], str(outp))
        print(f"Wrote pseudo to {outp} ({outp.stat().st_size/1024:.1f} KB)")
    if args.graph:
        gp=Path(args.graph)
        gp.parent.mkdir(parents=True, exist_ok=True)
        with open(gp,'w',encoding='utf-8') as f:
            f.write("digraph ModLoader {\n  rankdir=LR;\n  node [shape=box,fontsize=10];\n")
            for src,cnt in info['calls'].items():
                # find caller? approximate: who calls src most? We'll just link CALL->target
                f.write(f'  "{src}" [label="{src}\\ncalled {cnt}x"];\n')
            # edges: need to parse who calls whom
            for idx,l in enumerate(lines):
                m=re.search(r'Call\s+@(\w+)', l)
                if m:
                    tgt=m.group(1)
                    # find enclosing label
                    # walk back to nearest :Label
                    caller="global"
                    for j in range(idx, max(-1, idx-500), -1):
                        if lines[j].startswith(':'):
                            caller=lines[j][1:].strip()
                            break
                    f.write(f'  "{caller}" -> "{tgt}";\n')
            f.write("}\n")
        print(f"Wrote graph to {gp}")

if __name__=='__main__':
    main()
