#!/usr/bin/env python3
"""export_docs.py — regenerate ALL derived naming docs from current maps.

Source of truth: tools/rename_map.json (+_full) and tools/verification_report.json.
Replaces: generate_naming.py, generate_full_naming.py, regen_defines.py (removed;
they baked in pre-audit heuristic names). Run: python3 tools/export_docs.py
"""
import json, pathlib

ROOT = pathlib.Path(__file__).parent.parent
DOCS = ROOT / 'docs'
d = json.load(open(ROOT / 'tools/rename_map.json'))
full = json.load(open(ROOT / 'tools/rename_map_full.json'))
rep = json.load(open(ROOT / 'tools/verification_report.json'))

def ev_text(entry):
    ev = entry.get('evidence') or []
    bits = []
    for item in ev:
        if isinstance(item, (list, tuple)) and len(item) == 2 and item[0] == '+':
            bits.append(str(item[1]))
    s = '; '.join(bits)
    return (s[:220] + '…') if len(s) > 220 else s

def labkey(lab):
    if lab.startswith('Label_') and lab[6:].isdigit():
        return (0, int(lab[6:]))
    return (1, lab)

HDR = '<!-- AUTO-GENERATED by tools/export_docs.py — do not hand-edit. Source: tools/rename_map.json + verification_report.json -->\n\n'

# 1) curated labels
L = d['labels']
rows = [f"| `{lab}` | `{L[lab]}` | {rep['labels'].get(lab, {}).get('verdict', '?')} | {ev_text(rep['labels'].get(lab, {}))} |"
        for lab in sorted(L, key=labkey)]
(DOCS / 'NAMING_MAP_LABELS.md').write_text(
    f"{HDR}# Naming Map — Labels ({len(rows)} curated)\n\n| Label | Name | Verdict | Evidence |\n|---|---|---|---|\n" + '\n'.join(rows) + '\n')

# 2) curated statics
def srow(bank, sid, nm):
    e = rep['statics'].get(f"S{bank}[{sid}]", {})
    return f"| `Static{bank}[{sid}]` | `{nm}` | {e.get('verdict', '?')} | {ev_text(e)} |"
s1 = [srow('1', k, d['statics1'][k]) for k in sorted(d['statics1'], key=int)]
s2 = [srow('2', k, d['statics2'][k]) for k in sorted(d['statics2'], key=int)]
(DOCS / 'NAMING_MAP_STATICS.md').write_text(
    f"{HDR}# Naming Map — Statics ({len(s1)} bank-1 + {len(s2)} bank-2)\n\n## Static1\n\n| Static | Name | Verdict | Evidence |\n|---|---|---|---|\n" +
    '\n'.join(s1) + f"\n\n## Static2\n\n| Static | Name | Verdict | Evidence |\n|---|---|---|---|\n" + '\n'.join(s2) + '\n')

# 3) full labels
FL = full['labels']
rows = [f"| `{lab}` | `{FL[lab]}` |" for lab in sorted(FL, key=labkey)]
(DOCS / 'NAMING_MAP_LABELS_FULL.md').write_text(
    f"{HDR}# Full Naming Map — Labels ({len(rows)} incl. auto `__J_` internals)\n\n> Curated names have semantic meaning; `__J_*` names are positional (owner + branch shape) for navigation.\n\n| Label | Name |\n|---|---|\n" + '\n'.join(rows) + '\n')

# 4) full statics
f1 = [f"| `Static1[{k}]` | `{full['statics1'][k]}` |" for k in sorted(full['statics1'], key=int)]
f2 = [f"| `Static2[{k}]` | `{full['statics2'][k]}` |" for k in sorted(full['statics2'], key=int)]
(DOCS / 'NAMING_MAP_STATICS_FULL.md').write_text(
    f"{HDR}# Full Naming Map — Statics ({len(f1)} + {len(f2)})\n\n## Static1\n\n| Static | Name |\n|---|---|\n" +
    '\n'.join(f1) + "\n\n## Static2\n\n| Static | Name |\n|---|---|\n" + '\n'.join(f2) + '\n')

# 5) glossary (curated only, alphabetical by name)
items = []
for lab in sorted(L, key=lambda l: L[l].lower()):
    e = rep['labels'].get(lab, {})
    items.append(f"### `{L[lab]}`\n- Label: `{lab}` · Verdict: **{e.get('verdict', '?')}**\n- {ev_text(e) or '—'}\n")
for bank, dd in (('1', d['statics1']), ('2', d['statics2'])):
    for sid in sorted(dd, key=lambda s: dd[s].lower()):
        e = rep['statics'].get(f"S{bank}[{sid}]", {})
        items.append(f"### `{dd[sid]}`\n- Static: `Static{bank}[{sid}]` · Verdict: **{e.get('verdict', '?')}**\n- {ev_text(e) or '—'}\n")
items.sort(key=str.lower)
(DOCS / 'REFERENCE_GLOSSARY.md').write_text(
    f"{HDR}# Reference Glossary ({len(items)} curated names, A–Z)\n\n" + '\n'.join(items))

# 6) defines header
out = [f"// AUTO-GENERATED by tools/export_docs.py — {len(L)} labels, {len(d['statics1'])}+{len(d['statics2'])} statics (+ full-map internals)",
       "// Usage: keep as cheatsheet, or #include-style reference for CSA splits.", ""]
out.append("// ---- curated labels ----")
for lab in sorted(L, key=labkey):
    n = lab[6:] if lab.startswith('Label_') and lab[6:].isdigit() else None
    out.append(f"#define {L[lab]} {lab}" if n is None else f"#define {L[lab]} Label_{n}")
out.append("")
out.append("// ---- curated statics ----")
for k in sorted(d['statics1'], key=int):
    out.append(f"#define {d['statics1'][k]} Static1[{k}]")
for k in sorted(d['statics2'], key=int):
    out.append(f"#define {d['statics2'][k]} Static2[{k}]")
out.append("")
out.append("// ---- full-map internals ----")
for lab in sorted(FL, key=labkey):
    if lab not in L:
        out.append(f"#define {FL[lab]} {lab}")
(DOCS / 'ModLoader_Defines.h').write_text('\n'.join(out) + '\n')

# 7) named statics copy
import re
stat_src = (ROOT / 'ModLoader_Statics.c').read_text(encoding='utf-8', errors='replace')
def tag(m):
    n = int(m.group(1))
    nm = d['statics1'].get(str(n), '')
    return f"{m.group(0)}  // {nm}" if nm else m.group(0)
named = re.sub(r'Static_(\d+)\s*=\s*[^;]+;', tag, stat_src)
(DOCS / 'ModLoader_Statics_Named.c').write_text(
    "// ModLoader_Statics_Named.c — AUTO-GENERATED by tools/export_docs.py\n"
    "// Named copy of ModLoader_Statics.c (flat Static_N; N<256 = bank 1).\n"
    "// Usage: #include this file instead of ModLoader_Statics.c\n\n" + named)
print('export_docs: 7 files regenerated')
