// ModLoader_Statics_Named.c — AUTO-GENERATED by tools/export_docs.py
// Named copy of ModLoader_Statics.c (flat Static_N; N<256 = bank 1).
// Usage: #include this file instead of ModLoader_Statics.c

// ModLoader_Statics_Named.c — auto-named from tools/rename_map.json
// Original: ModLoader_Statics.c (27 lines)
// Naming: docs/NAMING_MAP_STATICS.md
// Usage: #include "ModLoader_Statics_Named.c" instead of ModLoader_Statics.c
// Every Static_N maps to a g* name, see also ModLoader_Defines.h for #defines

Static_175 = 10;  // gMenu_PageStack_0  // gTheme_Custom_R1

Static_186 = 10;  // gMenu_SelStack_0  // gTheme_Custom_R2

Static_203 = 1;  // gSplash_ShowOpenHint  // gTheme_PaletteId

Static_209 = 4;  // gUI_Hdr_R  // gUI_Hdr_R

Static_210 = 252;  // gUI_Hdr_G  // gUI_Hdr_G

Static_211 = 255;  // gUI_Hdr_B  // gUI_Hdr_B

Static_212 = 255;  // gUI_Hdr_A  // gUI_Hdr_A

Static_215 = 4;  // gUI_PlayerNameR  // gUnk1_215

Static_216 = 255;  // gUI_PlayerNameG  // gUnk1_216

Static_217 = 255;  // gUI_PlayerNameB  // gUnk1_217

Static_218 = 255;  // gUI_PlayerNameA  // gUnk1_218

Static_219 = 7;  // gUI_WelcomeR  // gUnk1_219

Static_220 = 255;  // gUI_WelcomeG  // gUnk1_220

Static_221 = 255;  // gUI_WelcomeB  // gUnk1_221

Static_222 = 255;  // gUI_WelcomeA  // gUnk1_222

Static_241 = 255;  // gTheme_TextSelectedR  // gUI_BG_R

Static_242 = 255;  // gTheme_TextSelectedG  // gUI_BG_G

Static_243 = 255;  // gTheme_TextSelectedB  // gUI_BG_B

Static_247 = 255;  // gUI_FG_R  // gUI_FG_R

Static_248 = 255;  // gUI_FG_G  // gUI_FG_G

Static_249 = 255;  // gUI_FG_B  // gUI_FG_B

Static_257 = 1;  // gDead_257_Init1  // gOutfit_Filter_Show

Static_258 = 250;  // gDead_258_Init250  // gOutfit_Scroll_R

Static_259 = 250;  // gDead_259_Init250  // gOutfit_Scroll_G

Static_260 = 250;  // gDead_260_Init250  // gOutfit_Scroll_B

Static_262 = 1;  // gDead_262_Init1  // gOutfit_PreviewEnabled

Static_268 = 255;  // gDead_268_Init255  // gText_R_Selected

Static_269 = 255;  // gDead_269_Init255  // gText_G_Selected

Static_270 = 255;  // gDead_270_Init255  // gText_B_Selected

